--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aspiration_registers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aspiration_registers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subject_code character varying(200) NOT NULL,
    student_id uuid NOT NULL,
    reason character varying(255) NOT NULL,
    semester character varying(300) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.aspiration_registers OWNER TO postgres;

--
-- Name: blacklist_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blacklist_token (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.blacklist_token OWNER TO postgres;

--
-- Name: classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    class_code character varying(200) NOT NULL,
    teacher_id uuid NOT NULL,
    major_id uuid,
    specialization_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.classes OWNER TO postgres;

--
-- Name: credit_classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.credit_classes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subject_code character varying(200) NOT NULL,
    teacher_id uuid NOT NULL,
    name character varying(30) NOT NULL,
    quantity integer NOT NULL,
    room text,
    semester character varying(300) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    group_name character varying(10),
    schedule json
);


ALTER TABLE public.credit_classes OWNER TO postgres;

--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(500) NOT NULL,
    major_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: majors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.majors (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(500) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.majors OWNER TO postgres;

--
-- Name: news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.news OWNER TO postgres;

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    send_to uuid NOT NULL,
    seen_date character varying(200),
    response text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone,
    token character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.password_reset_token OWNER TO postgres;

--
-- Name: password_reset_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    reset_token character varying(200),
    expired character varying(50),
    user_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.password_tokens OWNER TO postgres;

--
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- Name: prerequisite_subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prerequisite_subjects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    register_code character varying(200) NOT NULL,
    prerequisite_code character varying(200) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.prerequisite_subjects OWNER TO postgres;

--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: specializations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specializations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(500) NOT NULL,
    major_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.specializations OWNER TO postgres;

--
-- Name: student_credit_classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_credit_classes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    credit_class_id uuid NOT NULL,
    scores text,
    exam_schedule text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.student_credit_classes OWNER TO postgres;

--
-- Name: student_majors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_majors (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    major_id uuid NOT NULL,
    specialization_id uuid,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.student_majors OWNER TO postgres;

--
-- Name: student_tuitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_tuitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    tuition_id uuid NOT NULL,
    endow double precision,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    paid double precision
);


ALTER TABLE public.student_tuitions OWNER TO postgres;

--
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_code character varying(200) NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    class_id uuid
);


ALTER TABLE public.students OWNER TO postgres;

--
-- Name: subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subjects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(500) NOT NULL,
    subject_code character varying(200) NOT NULL,
    major_id uuid,
    specialization_id uuid,
    number_of_credit double precision,
    ingredient_secretion json NOT NULL,
    semester character varying(300) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.subjects OWNER TO postgres;

--
-- Name: teachers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teachers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    teacher_code character varying(200) NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.teachers OWNER TO postgres;

--
-- Name: time_registers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.time_registers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    type_semester character varying(300),
    type_register character varying(300),
    open_time character varying(100) NOT NULL,
    end_time character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    version bigint
);


ALTER TABLE public.time_registers OWNER TO postgres;

--
-- Name: tuitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tuitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    semester character varying(100) NOT NULL,
    year character varying(50) NOT NULL,
    academic_year character varying(20) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    price double precision NOT NULL
);


ALTER TABLE public.tuitions OWNER TO postgres;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(15) NOT NULL,
    date_of_birth character varying(50) NOT NULL,
    gender character varying(10) NOT NULL,
    address character varying(150) NOT NULL,
    status character varying(150) NOT NULL,
    academic_year character varying(20),
    education_level character varying(30),
    is_online boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: aspiration_registers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.aspiration_registers (id, subject_code, student_id, reason, semester, created_at, updated_at) FROM stdin;
b3af4803-b3d9-464c-aeca-6166c2c2a7fa	sadsd	cff4b2bd-99ce-4f43-9e92-a6d890d022ab	<p><br></p>	Học kỳ 2	2025-12-17 11:13:21.596747+07	2025-12-17 11:13:21.596747+07
2c9020fb-cec9-4e7d-b213-623b1c686c6f	TSUBJ2	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	Mon tu chon	2025-1	2025-12-17 16:23:22.593798+07	2025-12-17 16:23:22.593798+07
39e7b663-beb3-4a6a-90fe-d9625d550f55	TSUBJ1_UPDATED	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	Cap nhat ly do	2025-1	2025-12-17 16:23:22.541817+07	2025-12-17 16:23:22.714982+07
\.


--
-- Data for Name: blacklist_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.blacklist_token (id, token, created_at, updated_at) FROM stdin;
7a9cdb87-ad83-4c68-83cc-1cdf3059037e	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsZXZpMmszZHNAZ21haWwuY29tIiwiaWF0IjoxNzYyNzcwMTk3LCJleHAiOjE3NjI4MDYxOTd9.UWKNuNm9kZfditWzCVBe4qu3hDfOFIyLdhdA5UkfEvg	2025-11-10 17:27:57.664243	2025-11-10 17:27:57.664243
c039eab0-478d-4521-9d45-f130690eb255	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsZXZpMmszZHNAZ21haWwuY29tIiwiaWF0IjoxNzYzNjk5NDUxLCJleHAiOjE3NjM3MzU0NTF9.7TDW2v0SddZee7aUH3rRtNKYWjV5htCiNi2KCr1A93A	2025-11-21 11:31:03.825232	2025-11-21 11:31:03.825232
16eb581b-5f92-4070-84ef-eb5c9088ce8e	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsZXZpMmszZHNAZ21haWwuY29tIiwiaWF0IjoxNzY1NDYwNjExLCJleHAiOjE3NjU0OTY2MTF9.UF77OzN3BkkduHk0hVK-uiIUXDF_AI4AOzjeOSiB6kA	2025-12-11 21:32:19.757696	2025-12-11 21:32:19.757696
bbe9c0af-5713-450c-822c-33cac9789a6c	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk1NjExMywiZXhwIjoxNzY1OTkyMTEzfQ.rCPeE2ugo-I6dKAPHHUMJLCWrjpG9TSv6_vqvq5mJjs	2025-12-17 14:31:10.284862	2025-12-17 14:31:10.284862
5dc089a9-7ea5-4f44-b1b1-8d505fe184f2	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk1NzAyNywiZXhwIjoxNzY1OTkzMDI3fQ.VS7faxWu3IOrcVsNgvMhe6Ct9GrUqoCdXtDjZP7trBg	2025-12-17 14:40:00.730412	2025-12-17 14:40:00.730412
05375c11-be60-4f4d-b6de-a53269678da4	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk1NzIxNiwiZXhwIjoxNzY1OTkzMjE2fQ.phCBBNO1Rl4ycvmJODa5qUTvDCiwF0QWj8lu0xrt7XQ	2025-12-17 14:54:07.019267	2025-12-17 14:54:07.020333
a63abc0b-4f88-4bad-bc3d-00365c1c54b7	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk1ODA1NywiZXhwIjoxNzY1OTk0MDU3fQ.z6qDJGjginGObm8o0mA-eMNgCuaTkskx3UHQrO0ImCg	2025-12-17 14:54:35.113831	2025-12-17 14:54:35.113831
85592b8c-46c3-43f7-80ab-11c0248b2c94	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtaW5oZHpAZ21haWwuY29tIiwiaWF0IjoxNzY1OTU4MDg3LCJleHAiOjE3NjU5OTQwODd9.8RcK7xj1nxzZ15C8uCwSizFsA0p_h2OhyUhYkb765_U	2025-12-17 14:58:16.697247	2025-12-17 14:58:16.697247
899022ae-490c-4941-90f3-a921578db690	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmh0dXNAZ21haWwuY29tIiwiaWF0IjoxNzY1OTU4MzEwLCJleHAiOjE3NjU5OTQzMTB9.-kjErM2bfYW0kvNVvyA4cLdyGyLnq0SJnILTYp1jjoU	2025-12-17 14:58:44.705458	2025-12-17 14:58:44.705458
0ccf3d3a-0433-42de-a5dc-2b087646cf7a	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk1ODMzNCwiZXhwIjoxNzY1OTk0MzM0fQ.ftA7tpqenoP6wbpj6NwwDvkM0Wn_z9XBmZgB5x0iEmM	2025-12-17 15:33:51.244707	2025-12-17 15:33:51.244707
567d2399-bfa1-4739-93e2-545f80e4a370	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk2MDQ0NiwiZXhwIjoxNzY1OTk2NDQ2fQ.jku4x99U57mobjAtN2wndyhkJraiUE5m1HGLChkPfRQ	2025-12-17 15:34:13.536894	2025-12-17 15:34:13.536894
6c8cc252-0338-4084-a60a-5538d57191bc	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk2MzQ4NSwiZXhwIjoxNzY1OTk5NDg1fQ.zZ_CJLsu03b_CQtD97cP0VajM-3jbJgrxg3VmwBw-iw	2025-12-17 16:24:45.172474	2025-12-17 16:24:45.172474
\.


--
-- Data for Name: classes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.classes (id, class_code, teacher_id, major_id, specialization_id, created_at, updated_at) FROM stdin;
08f370d6-2b94-4617-b6c5-882633ac8512	abc	6a5fb6ba-08bb-4c66-b0c6-3476c863a1f6	8b352b85-4e9e-4814-bb71-06d51580ac60	\N	2025-12-13 15:02:46.512195+07	2025-12-13 15:02:46.512195+07
957a9d29-7cbf-438d-88eb-74dc7b8c056e	CLTEST002	ddd9840b-7f1e-4371-b411-a5001c86a3a4	84b3da84-f02a-4f32-9906-100237ddde7d	\N	2025-12-17 16:21:59.742625+07	2025-12-17 16:21:59.742625+07
e8995425-a17c-4fb7-9980-e84f3ad727a1	CLTEST001_UPD	ddd9840b-7f1e-4371-b411-a5001c86a3a4	84b3da84-f02a-4f32-9906-100237ddde7d	ce8e3b4f-2611-48e5-9143-35d4fe77f8f6	2025-12-17 16:21:59.687351+07	2025-12-17 16:21:59.808483+07
\.


--
-- Data for Name: credit_classes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.credit_classes (id, subject_code, teacher_id, name, quantity, room, semester, created_at, updated_at, group_name, schedule) FROM stdin;
139ae00d-1b9c-4da2-b5af-03579cf7b95b	CS201	6a5fb6ba-08bb-4c66-b0c6-3476c863a1f6	Intro to AI 1764135757	40	B201	2024-2025	2025-11-26 12:42:38.00334+07	2025-12-17 10:10:04.254534+07	G1	[{"room": "602", "endDate": "2026-02-28", "dayOfWeek": "2", "startDate": "2025-12-18", "startPeriod": 1, "numberOfPeriods": 2}]
1798d5fa-c8e2-4b6a-bb85-aa598dbefdd4	TSUBJ2	ddd9840b-7f1e-4371-b411-a5001c86a3a4	LTC_TEST_2	60	A102	2025-1	2025-12-17 16:22:20.500575+07	2025-12-17 16:22:20.501575+07	1	\N
ec50500a-b5e8-43d9-9615-2a4a4a4db256	TSUBJ1_UPDATED	ddd9840b-7f1e-4371-b411-a5001c86a3a4	LTC_TEST_1_UPD	55	A201	2025-1	2025-12-17 16:22:20.44767+07	2025-12-17 16:22:20.538353+07	1	\N
\.


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (id, name, major_id, created_at, updated_at) FROM stdin;
398ded6f-0a4d-423a-80d1-7f9248111f67	Công nghệ thông tin 1	8b352b85-4e9e-4814-bb71-06d51580ac60	2025-12-17 10:07:42.730233+07	2025-12-17 10:07:42.730233+07
b39bb2fc-cf6f-4e26-8c41-a2aea2870f78	Khoa viễn thông 2	a1b6c515-52a3-409b-9a65-4af199d58527	2025-12-08 21:18:23.04333+07	2025-12-17 10:07:47.492615+07
2ac39034-dce3-4a0a-9b66-e293ea8e2492	TEST_DEPT_2	fec4efcc-5899-493e-8bf9-23a7b3d93801	2025-12-17 16:14:33.073555+07	2025-12-17 16:14:33.073555+07
c84f947b-5611-4140-bd07-3a652a5c03e1	TEST_DEPT_1_UPDATED	84b3da84-f02a-4f32-9906-100237ddde7d	2025-12-17 16:14:33.014615+07	2025-12-17 16:14:33.120899+07
\.


--
-- Data for Name: majors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.majors (id, name, created_at, updated_at) FROM stdin;
a1b6c515-52a3-409b-9a65-4af199d58527	vien thong	2025-11-15 16:40:09.077902+07	2025-11-15 16:40:09.077902+07
e5188b15-530d-4efb-bfcd-fa90c9f385ea	dien - dien tu	2025-11-16 13:57:43.740152+07	2025-11-16 13:57:43.740152+07
8b352b85-4e9e-4814-bb71-06d51580ac60	Công nghệ thông tin	2025-12-08 21:02:43.86936+07	2025-12-08 21:02:43.86936+07
84b3da84-f02a-4f32-9906-100237ddde7d	TEST_MAJOR_1_UPDATED	2025-12-17 16:11:49.102065+07	2025-12-17 16:14:50.40739+07
fec4efcc-5899-493e-8bf9-23a7b3d93801	TEST_MAJOR_0	2025-12-17 16:11:49.158078+07	2025-12-18 14:47:09.331937+07
\.


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news (id, title, content, created_at, updated_at) FROM stdin;
29792bf1-4985-464b-8b04-a8c8314b3c00	Tiêu đề thông báo 8	Nội dung thông báo 9	2025-11-15 21:40:25.349881+07	2025-11-15 21:40:25.350905+07
fd48f200-c71c-418b-82fe-7e56c2d4ea11	Tiêu đề thông báo 8	Nội dung thông báo 9	2025-11-15 21:40:55.928923+07	2025-11-15 21:40:55.928923+07
524e877b-8d58-4433-bb57-a511ecda17a3	hello	hello anh em nhé	2025-12-08 19:51:12.851329+07	2025-12-08 19:51:12.851329+07
2ec70680-c1e9-49ea-a8af-fc4ba1532c76	Test News 2	Noi dung test 2	2025-12-17 16:24:01.370576+07	2025-12-17 16:24:01.370576+07
d0aa4f63-45a7-4c20-b184-e646143875f6	Test News 1 Updated	Noi dung test 1 updated	2025-12-17 16:24:01.307865+07	2025-12-17 16:24:01.504296+07
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, title, content, send_to, seen_date, response, created_at, updated_at) FROM stdin;
d83f3e81-0822-4426-a9be-fca9349629ea	Tiêu đề thông báo 1	Nội dung thông báo 2	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-11-15T16:57:29.492953100+07:00	\N	2025-11-15 16:56:22.431227+07	2025-11-15 16:57:29.501419+07
1171e202-2662-410a-b14c-fa28c700e49e	123123123	<p>123123123123</p>	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-12-14T15:18:50.649011900+07:00	<p>oke nha</p>	2025-12-13 15:04:39.742973+07	2025-12-14 15:28:18.965773+07
02f149bc-7ee2-4848-9e17-bd64bd3f7826	Tiêu đề thông báo	Nội dung thông báo	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-12-14T15:37:33.922510700+07:00	Nội dung phản hồi	2025-11-15 16:55:48.894062+07	2025-12-14 15:37:33.925831+07
b3d9af0f-8fd5-4291-936d-0d87484f7804	Hello em	<p>heheheh</p>	27d91e1b-70dc-4d48-a2f5-34736908d154	\N	\N	2025-12-17 10:18:00.296558+07	2025-12-17 10:18:00.296558+07
f7ba767f-2a54-49ea-bca9-92e264e180ec	Thong bao 1	Noi dung thong bao 1	1ef3f5ff-c0e2-4384-9168-cfce91123745	2025-12-17T16:24:30.829675300+07:00	\N	2025-12-17 16:24:30.737485+07	2025-12-17 16:24:30.829675+07
2f4f1740-845a-4bec-9246-a9cc1f387d32	Thong bao 2	Noi dung thong bao 2	1ef3f5ff-c0e2-4384-9168-cfce91123745	\N	Da doc thong bao 2	2025-12-17 16:24:30.7944+07	2025-12-17 16:24:30.841672+07
\.


--
-- Data for Name: password_reset_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_token (id, expiry_date, token, user_id) FROM stdin;
\.


--
-- Data for Name: password_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_tokens (id, reset_token, expired, user_id, created_at, updated_at) FROM stdin;
1cd0a2eb-4e19-4d7c-a328-cf935eeba5c4	935bb96e-7aac-4e5e-8561-1786ffd7a8f2	false	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-11-12 16:27:31.240066+07	2025-11-12 16:27:31.241622+07
91aa0618-ef80-4447-9bff-da5464ed96bb	4faf283f-c0ad-444f-bb0f-18a26b5cc2be	false	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-11-16 13:56:01.378821+07	2025-11-16 13:56:01.378821+07
8e678209-14cc-4a06-8a23-145fd9cf329e	ab342e0a-04e5-4f26-9fcc-3d6a75af8dcb	false	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-11-26 12:17:08.606312+07	2025-11-26 12:17:08.606996+07
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permissions (id, name, created_at, updated_at) FROM stdin;
4644906d-5795-4bdb-a983-74630bc79194	AUTH_LOGIN	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
6038ad94-ff00-4140-a2f2-f72ed967ed1c	AUTH_LOGOUT	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
b2b3ca8b-61ea-42ea-9421-247d6b6b2e05	PASSWORD_RESET_REQUEST	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
6122fe64-4a2a-443d-8883-b0e47ec76edf	PASSWORD_RESET_VALIDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
8b98b116-b212-4e16-aa23-dd15d0d97a99	PASSWORD_RESET_SUBMIT	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
4126c61b-117b-4eec-8758-9b8fcb6d9155	USER_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
2c9267d0-2fef-41fc-8cb5-be5722e45f65	USER_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
80e01d5e-1bc7-48ea-bb83-9bd5db4dbf5e	USER_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
a2200cc7-fba3-4786-912c-0fd4c485fbc4	USER_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
ddcb7eff-392e-43c8-98cc-23bd26e60f32	USER_CHANGE_STATUS	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
ae32e94e-24b6-4df8-8405-f6dcef9f0dfa	ROLE_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
9d896100-7e44-4d35-9d51-fb8ff35699d0	ROLE_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
d49ae92a-75e0-4ab5-a370-f3624bf81861	ROLE_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
f935de55-a7c2-4d25-af95-87c57565a552	ROLE_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
157c2a5a-c12f-4f01-b852-29a9371bb91a	PERMISSION_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
f5e17cb6-9fe6-4cc6-a092-a15460a022c7	PERMISSION_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
24bfd7e3-391f-48fd-85a0-0f5f79b71946	PERMISSION_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
b623f73a-987a-41a0-b6c2-8b3b1902d7b1	PERMISSION_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
75dcd2d0-3306-4664-90c6-3acd9901b18c	USER_ROLE_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
e4da47fe-fd64-49b6-9afe-c344302c6aca	USER_ROLE_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
c7a11014-4d9c-4364-9dbd-fb5fb32de982	USER_ROLE_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
9494bbf9-f0fd-4a90-bc96-d43eded94845	USER_ROLE_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
7811f510-ee5e-4281-94f0-ee986771e392	ROLE_PERMISSION_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
593bc57c-830f-48b6-bd18-48381f864e02	ROLE_PERMISSION_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
d30ec658-4063-4a39-af8b-2a2515e1a21e	ROLE_PERMISSION_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
fdb16fb0-3f45-4c94-86a6-066759aae343	ROLE_PERMISSION_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
47c5c47b-2c5d-417d-b4a8-86f7f61ad394	STUDENT_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
18fce808-da17-49af-8b4d-43fe56d66422	STUDENT_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
635054ad-083b-45ba-b77f-eab35f5c7f8a	STUDENT_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
79125d71-6529-49dd-84b5-7248eb2b680b	STUDENT_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
a628fb25-979c-450d-9e75-911c3998b80b	STUDENT_VIEW_TRAINING_PROGRAM	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
d1b7efa2-afce-460e-8552-94f0a8ee5040	TEACHER_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
ec7271ef-678f-4617-a996-27116ea407c2	TEACHER_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
2d176eda-95a2-474a-9e2a-a1ac43f7c8dd	TEACHER_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
c71cd727-8e2f-470c-9699-b38e70f7910d	TEACHER_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
4c061bb2-e024-42bb-9fac-6a1277377d55	LECTURER_VIEW_PROFILE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
4acae5d1-3d09-4700-9b82-fb52659f7c14	LECTURER_VIEW_CLASSES	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
5eea132d-018c-4d6c-9eac-467e9c40ab62	LECTURER_VIEW_STUDENTS	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
bcb2a99e-7ddc-4ae1-9f4f-afa9fa1d2701	LECTURER_UPDATE_GRADE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
770eebf4-9313-44c1-a866-79e33cad0308	LECTURER_VIEW_SCHEDULE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
f9b33c16-0f98-4ef5-a614-d3fc421478e0	LECTURER_VIEW_ADMIN_CLASSES	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
febfd0f5-ed92-4a50-9bfb-e6cbf8fc65c3	LECTURER_VIEW_ADMIN_CLASS_STUDENTS	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
0f6df0ae-9164-4b7d-b78c-41c7995c7a5c	MAJOR_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
e3c15321-870a-4cb5-9130-e753eee6844a	MAJOR_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
735daad3-2205-4d0c-9e79-36843a5a631b	MAJOR_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
91d09312-3b51-48b0-8dcd-89e14995b6c6	MAJOR_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
f9cec2c7-d403-409a-8469-e5739ed5bf0a	SPECIALIZATION_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
68c7ed4d-043f-4398-864f-3a0b9f436a1f	SPECIALIZATION_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
cb071077-166f-4af1-ac32-8cba79e9eafc	SPECIALIZATION_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
a937c602-98bb-40f7-b7f7-c5c96f7e1535	SPECIALIZATION_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
933cb823-4104-498b-990d-34c1e2412771	DEPARTMENT_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
d67d4495-9fdb-4bc0-9600-b0e5b89d4a65	DEPARTMENT_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
fd3c9115-34af-467d-876c-36aad9ae0fd0	DEPARTMENT_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
9d6bde38-c3d3-45e5-b8ad-91436de1cf83	DEPARTMENT_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
6cfe2117-360c-4762-91c0-14df40c6082e	SUBJECT_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
dd0dd946-9edb-4deb-80dc-bbd05af15c23	SUBJECT_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
5df156a7-ecb7-4245-8e84-dd900b7492cc	SUBJECT_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
6bb7c03c-c7fd-427e-874f-2264807f7a35	SUBJECT_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
4703b48f-a8e6-42fa-882e-ddc940f76012	PREREQUISITE_SUBJECT_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
8e3c31fe-b354-4790-a811-eb6e9f66b2c5	PREREQUISITE_SUBJECT_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
b08fcda4-b19a-4f72-8ca2-89b6d3f6d29e	PREREQUISITE_SUBJECT_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
eb6d527b-b55d-44ad-b003-050cddac6ee9	PREREQUISITE_SUBJECT_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
c1f46884-943c-48bd-aefb-eaa55f7928b2	CLASS_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
99a807b8-aab1-401a-a98f-916599cf6b40	CLASS_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
dee32137-c8df-459f-a72f-c532e4d29d63	CLASS_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
23c56d53-04a4-4396-84b1-b153bccbf9ce	CLASS_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
c0f29a2e-e3f7-45b0-a774-300c286c9978	CREDIT_CLASS_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
7ec614bf-b0c5-467b-83d7-10150d6e0375	CREDIT_CLASS_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
523dc287-18c3-45d6-9317-29f45aefb648	CREDIT_CLASS_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
bec29a0c-58fb-4c4f-85ec-92a545427aee	CREDIT_CLASS_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
9e539eb1-88d7-4222-a9ef-679c032541f8	STUDENT_CREDIT_CLASS_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
d4cb5bd1-d1e8-421e-bed4-4c78bf89e17e	STUDENT_CREDIT_CLASS_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
36898708-62ef-4389-a9bf-88c63ddbb614	STUDENT_CREDIT_CLASS_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
42c2ed80-6ab2-4ee4-aeb1-5354e79faa36	STUDENT_CREDIT_CLASS_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
b3bfda7c-20df-433e-8e0b-0c02e212a655	TIME_REGISTER_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
0aca692b-72bf-438e-ba3a-8025ea2a7963	TIME_REGISTER_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
7533470d-a495-4a3c-897f-849bbbd49398	TIME_REGISTER_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
17ace5fa-2e74-4abb-aa24-0c31f4388caa	TIME_REGISTER_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
9dd9d868-ef78-4cab-ad08-8381092c21b6	ASPIRATION_REGISTER_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
f057c669-4400-4565-a870-4df9bedbbf49	ASPIRATION_REGISTER_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
677281d4-5e77-44f6-8f99-6a32cc624510	ASPIRATION_REGISTER_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
21682e76-31ba-4a9b-b9a7-a28e449f8ba0	ASPIRATION_REGISTER_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
8576de8f-f2d2-422d-9815-c22bc23305f9	STUDENT_MAJOR_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
62d6f35d-516b-491f-b8cd-21bdd7080a44	STUDENT_MAJOR_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
6326c733-680a-4cc3-b95b-38e17a8cfb94	STUDENT_MAJOR_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
a51159f5-0b6d-4782-b873-2c7788458db7	STUDENT_MAJOR_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
37b924fd-3837-49b6-8b14-7b4198766495	TUITION_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
db8bcfa7-ab14-4008-9fd0-5dc939adaa89	TUITION_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
024523c6-db7f-4dcf-8171-0e05bf557efa	TUITION_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
4d56d10a-8512-420d-acd6-885d6384b530	TUITION_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
1c9eaa8c-2c55-4cd0-b552-ec003344536f	STUDENT_TUITION_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
b60a7c54-9a90-4eb2-9fe7-f42ac1ffd52a	STUDENT_TUITION_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
54e8a098-19b7-467f-94d6-2daa90149dee	STUDENT_TUITION_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
e68ec1b3-96ee-4c35-99c2-0ca7b254ffc6	STUDENT_TUITION_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
6ee8bd4c-fc79-4f7b-b143-db8d1d72e732	NEWS_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
ed3b8687-c636-43ef-a7fe-eded8e557a08	NEWS_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
9f2b9d5e-6830-4f69-84dc-3b9068aafe56	NEWS_UPDATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
3ad5b31d-80f5-455a-b4e4-ff5967a56f05	NEWS_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
8e6635c9-119f-4fde-8788-a2552d584848	NEWS_DELETE_BATCH	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
d20eb58b-8f9c-45cc-9348-55570ac47920	NOTIFICATION_VIEW	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
7f963daa-a724-4c92-950c-83ffa215f367	NOTIFICATION_CREATE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
fa33a10b-d47f-48eb-9d31-d19de167b1c0	NOTIFICATION_UPDATE_RESPONSE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
1e4fa2ad-ede0-4659-819b-bd583abadbb1	NOTIFICATION_MARK_SEEN	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
72d75dfa-b484-4dae-97e7-9a3fe09278dd	NOTIFICATION_DELETE	2025-12-17 13:04:46.331132	2025-12-17 13:04:46.331132
aab17630-f73b-4165-b622-cdfd1e5cbc5a	TEST_PERMISSION_2	2025-12-17 09:07:37.058987	2025-12-17 09:07:37.058987
9467767e-c991-49a9-bebb-0d8b5e327507	TEST_PERMISSION_1_UPDATED	2025-12-17 09:07:37.047649	2025-12-17 09:07:53.01157
\.


--
-- Data for Name: prerequisite_subjects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prerequisite_subjects (id, register_code, prerequisite_code, created_at, updated_at) FROM stdin;
3ac1d27b-9bb5-4024-a373-2ffa582ef251	sadsd	CS201	2025-12-13 15:05:16.063946+07	2025-12-17 10:21:27.572257+07
5fef2ae0-4d25-4465-82e4-db6d83cb7196	TSUBJ2	TSUBJ1_UPDATED	2025-12-17 16:15:42.992278+07	2025-12-17 16:15:42.992278+07
0f7857ad-ad01-4274-b83a-88ba1889ec7e	TSUBJ1_UPDATED_V2	TSUBJ2	2025-12-17 16:15:42.986295+07	2025-12-17 16:15:43.059887+07
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (id, role_id, permission_id, created_at, updated_at) FROM stdin;
3f09930a-7a04-44dc-9c4a-3d9d1a8e8e9d	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	4644906d-5795-4bdb-a983-74630bc79194	2025-12-17 13:20:24.403718	2025-12-17 13:20:24.403718
d05c8c97-c29e-4ce1-b1c6-4cd5c19ffec5	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	6038ad94-ff00-4140-a2f2-f72ed967ed1c	2025-12-17 13:20:24.437737	2025-12-17 13:20:24.437737
0d1af48a-6aef-4d61-ba40-7414b8e27fae	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	b2b3ca8b-61ea-42ea-9421-247d6b6b2e05	2025-12-17 13:20:24.441741	2025-12-17 13:20:24.441741
0d6fc3d8-26f2-49de-bbd8-115abcd24a04	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	6122fe64-4a2a-443d-8883-b0e47ec76edf	2025-12-17 13:20:24.445903	2025-12-17 13:20:24.445903
cb31069b-8da4-4dd7-8131-848efe655817	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	8b98b116-b212-4e16-aa23-dd15d0d97a99	2025-12-17 13:20:24.45044	2025-12-17 13:20:24.45044
811f578b-1cf8-4de2-aa49-53a5e4162d0c	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	4126c61b-117b-4eec-8758-9b8fcb6d9155	2025-12-17 13:20:24.457895	2025-12-17 13:20:24.457895
e79a8a88-84ca-4c97-b190-4b70fe4177c9	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	2c9267d0-2fef-41fc-8cb5-be5722e45f65	2025-12-17 13:20:24.462895	2025-12-17 13:20:24.462895
3e611792-39ed-49b6-8fde-cfc0389dc1f0	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	80e01d5e-1bc7-48ea-bb83-9bd5db4dbf5e	2025-12-17 13:20:24.467405	2025-12-17 13:20:24.467405
2e4bc239-1a0b-4a27-aca7-e7a9a8ca2cbb	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	a2200cc7-fba3-4786-912c-0fd4c485fbc4	2025-12-17 13:20:24.474405	2025-12-17 13:20:24.474405
7cf5d8dd-3eed-4679-b556-c4ac78626ba6	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	ddcb7eff-392e-43c8-98cc-23bd26e60f32	2025-12-17 13:20:24.478598	2025-12-17 13:20:24.478598
8a2bad4e-3117-4781-b647-852ebe23d9e5	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	ae32e94e-24b6-4df8-8405-f6dcef9f0dfa	2025-12-17 13:20:24.483667	2025-12-17 13:20:24.483667
10a85071-8cd3-4b2d-b07f-9ca7bdb567d3	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	9d896100-7e44-4d35-9d51-fb8ff35699d0	2025-12-17 13:20:24.490121	2025-12-17 13:20:24.490121
e4861d2b-3c99-4308-a629-3bc65087ea30	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	d49ae92a-75e0-4ab5-a370-f3624bf81861	2025-12-17 13:20:24.49512	2025-12-17 13:20:24.49512
b54d6447-37a4-4d4c-a882-b8ce9bb78815	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	f935de55-a7c2-4d25-af95-87c57565a552	2025-12-17 13:20:24.499599	2025-12-17 13:20:24.499599
54379213-ee55-4f16-8ca8-190dbb2ccf6c	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	157c2a5a-c12f-4f01-b852-29a9371bb91a	2025-12-17 13:20:24.507214	2025-12-17 13:20:24.507214
04004339-9d64-4737-bb1d-c158df83bd94	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	f5e17cb6-9fe6-4cc6-a092-a15460a022c7	2025-12-17 13:20:24.5136	2025-12-17 13:20:24.5136
b7c1346e-23ec-4e8f-9241-0226821d259d	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	24bfd7e3-391f-48fd-85a0-0f5f79b71946	2025-12-17 13:20:24.517644	2025-12-17 13:20:24.517644
bd57002f-5366-46a2-89ad-37735c3fd374	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	b623f73a-987a-41a0-b6c2-8b3b1902d7b1	2025-12-17 13:20:24.526255	2025-12-17 13:20:24.526255
f0d53604-aac2-4af7-b8b9-077abb8e64ea	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	75dcd2d0-3306-4664-90c6-3acd9901b18c	2025-12-17 13:20:24.530258	2025-12-17 13:20:24.530258
037738be-ad54-4b9f-8be8-a1d470a4e179	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	e4da47fe-fd64-49b6-9afe-c344302c6aca	2025-12-17 13:20:24.534258	2025-12-17 13:20:24.534258
91848e6f-9a1c-4bc2-8c25-0512c782b670	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	c7a11014-4d9c-4364-9dbd-fb5fb32de982	2025-12-17 13:20:24.541649	2025-12-17 13:20:24.541649
46ca5bf0-4193-44b5-b12f-d81debf82fe9	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	9494bbf9-f0fd-4a90-bc96-d43eded94845	2025-12-17 13:20:24.545656	2025-12-17 13:20:24.545656
e77655cf-34eb-4e31-bd87-f09df03c9f24	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	7811f510-ee5e-4281-94f0-ee986771e392	2025-12-17 13:20:24.54973	2025-12-17 13:20:24.54973
1018aa7a-6a63-47f9-851f-1df0125d2e77	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	593bc57c-830f-48b6-bd18-48381f864e02	2025-12-17 13:20:24.557026	2025-12-17 13:20:24.557026
fb35e649-cc32-4829-8de8-9f93cd9b329e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	d30ec658-4063-4a39-af8b-2a2515e1a21e	2025-12-17 13:20:24.560192	2025-12-17 13:20:24.560192
f4f42f7b-15a4-4c6e-95d7-afe25d1c6608	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	fdb16fb0-3f45-4c94-86a6-066759aae343	2025-12-17 13:20:24.564587	2025-12-17 13:20:24.564587
46a0c292-8ac2-4a26-8cd8-7824bd1a2b8c	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	47c5c47b-2c5d-417d-b4a8-86f7f61ad394	2025-12-17 13:20:24.571105	2025-12-17 13:20:24.571105
f3868d60-537c-494d-aad1-a879770147eb	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	18fce808-da17-49af-8b4d-43fe56d66422	2025-12-17 13:20:24.575106	2025-12-17 13:20:24.575106
8a4d0b39-3782-43b6-a629-86cb0dc44ae0	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	635054ad-083b-45ba-b77f-eab35f5c7f8a	2025-12-17 13:20:24.579295	2025-12-17 13:20:24.579295
b77f92c1-6546-4e0e-a145-85641bee61eb	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	79125d71-6529-49dd-84b5-7248eb2b680b	2025-12-17 13:20:24.587839	2025-12-17 13:20:24.587839
064d0e1c-2abb-48da-9c6b-0373a46cc7a2	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	a628fb25-979c-450d-9e75-911c3998b80b	2025-12-17 13:20:24.59191	2025-12-17 13:20:24.59191
790da4f5-16d3-4675-89a5-e419a6dc8849	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	d1b7efa2-afce-460e-8552-94f0a8ee5040	2025-12-17 13:20:24.596802	2025-12-17 13:20:24.596802
63b2a59e-80d9-45cd-a02f-190770f6c2c9	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	ec7271ef-678f-4617-a996-27116ea407c2	2025-12-17 13:20:24.603814	2025-12-17 13:20:24.603814
9d3f10b0-7d37-4dce-b6d8-fda6771758e9	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	2d176eda-95a2-474a-9e2a-a1ac43f7c8dd	2025-12-17 13:20:24.607873	2025-12-17 13:20:24.607873
759499c4-bb1b-48fe-b214-33faac79ecb7	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	c71cd727-8e2f-470c-9699-b38e70f7910d	2025-12-17 13:20:24.611172	2025-12-17 13:20:24.611172
9d069298-9f04-475a-9059-b558f905ae78	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	4c061bb2-e024-42bb-9fac-6a1277377d55	2025-12-17 13:20:24.618742	2025-12-17 13:20:24.618742
e46464db-2fa1-490f-890c-f5d512e32d37	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	4acae5d1-3d09-4700-9b82-fb52659f7c14	2025-12-17 13:20:24.623059	2025-12-17 13:20:24.623059
9a16fe2c-0f84-4e31-8db4-78caf723e179	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	5eea132d-018c-4d6c-9eac-467e9c40ab62	2025-12-17 13:20:24.626578	2025-12-17 13:20:24.626578
6f2f8473-2b46-4a46-8a24-bd292941ae5c	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	bcb2a99e-7ddc-4ae1-9f4f-afa9fa1d2701	2025-12-17 13:20:24.629596	2025-12-17 13:20:24.629596
95a1237e-5a13-461b-9c8d-b842a4dd34fb	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	770eebf4-9313-44c1-a866-79e33cad0308	2025-12-17 13:20:24.636104	2025-12-17 13:20:24.636104
df9665b9-bb15-4b80-87c9-fc8581317b0b	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	f9b33c16-0f98-4ef5-a614-d3fc421478e0	2025-12-17 13:20:24.639209	2025-12-17 13:20:24.639209
ce50b7f5-2c0c-4829-88f4-bf40b3f1e60e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	febfd0f5-ed92-4a50-9bfb-e6cbf8fc65c3	2025-12-17 13:20:24.642318	2025-12-17 13:20:24.642318
6eda24e6-1325-4dc4-9b33-e93cbdaf5685	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	0f6df0ae-9164-4b7d-b78c-41c7995c7a5c	2025-12-17 13:20:24.646723	2025-12-17 13:20:24.646723
7fbdc7cc-6be4-4e29-af3d-8ac665d2d6f0	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	e3c15321-870a-4cb5-9130-e753eee6844a	2025-12-17 13:20:24.654115	2025-12-17 13:20:24.654115
20c4d586-652e-4599-82d0-2918ba0230f6	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	735daad3-2205-4d0c-9e79-36843a5a631b	2025-12-17 13:20:24.658248	2025-12-17 13:20:24.658248
1b14e341-64e3-40e5-b08a-a5628d70aa10	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	91d09312-3b51-48b0-8dcd-89e14995b6c6	2025-12-17 13:20:24.661247	2025-12-17 13:20:24.661247
de605fbf-a8c8-44f1-9792-c3f222320bf0	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	f9cec2c7-d403-409a-8469-e5739ed5bf0a	2025-12-17 13:20:24.665765	2025-12-17 13:20:24.665765
8a11dd6e-76ba-47c9-b945-12a9795c2c55	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	68c7ed4d-043f-4398-864f-3a0b9f436a1f	2025-12-17 13:20:24.670774	2025-12-17 13:20:24.670774
d6b18b65-f725-4066-a614-731fa78147d4	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	cb071077-166f-4af1-ac32-8cba79e9eafc	2025-12-17 13:20:24.675888	2025-12-17 13:20:24.675888
ecb53085-9efb-4a36-8ef9-ffde1df1bc4f	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	a937c602-98bb-40f7-b7f7-c5c96f7e1535	2025-12-17 13:20:24.681137	2025-12-17 13:20:24.681137
aec8ce74-fd21-4de5-8aa3-e5b78090b23e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	933cb823-4104-498b-990d-34c1e2412771	2025-12-17 13:20:24.688827	2025-12-17 13:20:24.688827
11b00e2c-31fc-4f74-abd9-86e1a35eda9f	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	d67d4495-9fdb-4bc0-9600-b0e5b89d4a65	2025-12-17 13:20:24.692826	2025-12-17 13:20:24.692826
ac83a0b4-284c-41cb-938f-8468c6e7e4c3	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	fd3c9115-34af-467d-876c-36aad9ae0fd0	2025-12-17 13:20:24.69703	2025-12-17 13:20:24.69703
ea435729-0fff-4785-87a8-cdc986e0de1c	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	9d6bde38-c3d3-45e5-b8ad-91436de1cf83	2025-12-17 13:20:24.705813	2025-12-17 13:20:24.705813
fb00ca10-4523-4a78-96d7-082c801af704	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	6cfe2117-360c-4762-91c0-14df40c6082e	2025-12-17 13:20:24.70982	2025-12-17 13:20:24.70982
d99f81bb-7c64-4e4d-8870-e89092362b58	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	dd0dd946-9edb-4deb-80dc-bbd05af15c23	2025-12-17 13:20:24.714824	2025-12-17 13:20:24.714824
5bf7db30-ad85-4386-8e15-d6762d65ee59	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	5df156a7-ecb7-4245-8e84-dd900b7492cc	2025-12-17 13:20:24.722455	2025-12-17 13:20:24.722455
9eae39cc-553c-48d1-bc9d-695f2823412b	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	6bb7c03c-c7fd-427e-874f-2264807f7a35	2025-12-17 13:20:24.726962	2025-12-17 13:20:24.726962
6d1f7344-3604-4479-a76d-a4b1fbc300ff	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	4703b48f-a8e6-42fa-882e-ddc940f76012	2025-12-17 13:20:24.730961	2025-12-17 13:20:24.730961
1ffdfa6d-1f67-41ec-acfb-c32b7c85ba4f	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	8e3c31fe-b354-4790-a811-eb6e9f66b2c5	2025-12-17 13:20:24.738518	2025-12-17 13:20:24.738518
8f13c727-940d-43c9-95ff-a8240c7c593a	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	b08fcda4-b19a-4f72-8ca2-89b6d3f6d29e	2025-12-17 13:20:24.743558	2025-12-17 13:20:24.743558
ed3aa6c1-9fad-467a-991d-2d6602254d4e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	eb6d527b-b55d-44ad-b003-050cddac6ee9	2025-12-17 13:20:24.749158	2025-12-17 13:20:24.749158
4c8509b7-e741-4f2a-ac7b-0690ad21d9e4	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	c1f46884-943c-48bd-aefb-eaa55f7928b2	2025-12-17 13:20:24.754147	2025-12-17 13:20:24.754147
ba2f70ea-9aaf-4dce-8eca-ce4935999348	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	99a807b8-aab1-401a-a98f-916599cf6b40	2025-12-17 13:20:24.759658	2025-12-17 13:20:24.759658
57703917-7b37-46ea-b425-67ff5bdf87ba	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	dee32137-c8df-459f-a72f-c532e4d29d63	2025-12-17 13:20:24.763665	2025-12-17 13:20:24.763665
03d6e8c8-da05-4e89-b421-4953e64dd9f9	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	23c56d53-04a4-4396-84b1-b153bccbf9ce	2025-12-17 13:20:24.770205	2025-12-17 13:20:24.770205
31d3ce39-5a14-47fc-87c4-06671a97f264	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	c0f29a2e-e3f7-45b0-a774-300c286c9978	2025-12-17 13:20:24.7742	2025-12-17 13:20:24.7742
45caa5e0-108f-48df-a8e0-a9bacd3533cc	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	7ec614bf-b0c5-467b-83d7-10150d6e0375	2025-12-17 13:20:24.777711	2025-12-17 13:20:24.777711
b8368d98-ee4b-4720-8eca-7fac32fbf985	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	523dc287-18c3-45d6-9317-29f45aefb648	2025-12-17 13:20:24.78171	2025-12-17 13:20:24.78171
c9d15330-5a16-40d2-8a0d-09cc5aa5307e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	bec29a0c-58fb-4c4f-85ec-92a545427aee	2025-12-17 13:20:24.787312	2025-12-17 13:20:24.787312
9262fec9-d2e0-442b-acc0-21f9d2c55aed	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	9e539eb1-88d7-4222-a9ef-679c032541f8	2025-12-17 13:20:24.791355	2025-12-17 13:20:24.791355
037bedae-b2d5-4b05-95e5-ac9be39dc35f	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	d4cb5bd1-d1e8-421e-bed4-4c78bf89e17e	2025-12-17 13:20:24.794313	2025-12-17 13:20:24.794313
ad7ead93-ea5c-4fe4-bd9c-121676b2d098	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	36898708-62ef-4389-a9bf-88c63ddbb614	2025-12-17 13:20:24.802837	2025-12-17 13:20:24.802837
6e45040f-85a8-4516-9414-0e312419e35e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	42c2ed80-6ab2-4ee4-aeb1-5354e79faa36	2025-12-17 13:20:24.808134	2025-12-17 13:20:24.808134
20182b0d-7902-43a3-bc4c-40477cb809de	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	b3bfda7c-20df-433e-8e0b-0c02e212a655	2025-12-17 13:20:24.812135	2025-12-17 13:20:24.812135
91a84815-68b7-44e8-be5c-d2b28b55f24a	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	0aca692b-72bf-438e-ba3a-8025ea2a7963	2025-12-17 13:20:24.81988	2025-12-17 13:20:24.81988
c990e4e6-4a52-43c3-b8d2-f0778737b133	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	7533470d-a495-4a3c-897f-849bbbd49398	2025-12-17 13:20:24.823879	2025-12-17 13:20:24.823879
ae73b29c-95dd-4655-bb27-6f78c236f5c1	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	17ace5fa-2e74-4abb-aa24-0c31f4388caa	2025-12-17 13:20:24.828016	2025-12-17 13:20:24.828016
78c08061-1d5e-491a-9876-84f98a89bd78	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	9dd9d868-ef78-4cab-ad08-8381092c21b6	2025-12-17 13:20:24.835031	2025-12-17 13:20:24.835031
27db72f0-c199-4064-9125-d1565ab5a557	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	f057c669-4400-4565-a870-4df9bedbbf49	2025-12-17 13:20:24.839127	2025-12-17 13:20:24.839127
b331e9dd-c457-447c-8e5f-c1f2a9a6c38c	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	677281d4-5e77-44f6-8f99-6a32cc624510	2025-12-17 13:20:24.842382	2025-12-17 13:20:24.842382
f90af0f2-1b13-49e6-a8aa-0d023c06b3f2	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	21682e76-31ba-4a9b-b9a7-a28e449f8ba0	2025-12-17 13:20:24.845882	2025-12-17 13:20:24.845882
de8fc190-24ab-4e96-89b1-3dd7eeda0d44	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	8576de8f-f2d2-422d-9815-c22bc23305f9	2025-12-17 13:20:24.852333	2025-12-17 13:20:24.852333
0bcccbfa-cf9f-4f45-9674-16127d9d583a	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	62d6f35d-516b-491f-b8cd-21bdd7080a44	2025-12-17 13:20:24.855825	2025-12-17 13:20:24.855825
e25fc659-b4ec-4522-97a1-1265eaf37dc1	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	6326c733-680a-4cc3-b95b-38e17a8cfb94	2025-12-17 13:20:24.859115	2025-12-17 13:20:24.859115
8f901634-c5d7-4c41-87ee-dbc327da2f56	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	a51159f5-0b6d-4782-b873-2c7788458db7	2025-12-17 13:20:24.862115	2025-12-17 13:20:24.862115
e02224b4-6b5d-4b20-b04c-cc79a7ba5749	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	37b924fd-3837-49b6-8b14-7b4198766495	2025-12-17 13:20:24.869154	2025-12-17 13:20:24.869154
bc4172d8-8a75-40dd-912c-fc0ca05d29c0	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	db8bcfa7-ab14-4008-9fd0-5dc939adaa89	2025-12-17 13:20:24.873153	2025-12-17 13:20:24.873153
d22450c4-2e8e-4f58-ac8a-326e4110a70e	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	024523c6-db7f-4dcf-8171-0e05bf557efa	2025-12-17 13:20:24.87582	2025-12-17 13:20:24.87582
30638d33-3940-4afb-8b47-dd5dd1a83764	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	4d56d10a-8512-420d-acd6-885d6384b530	2025-12-17 13:20:24.877827	2025-12-17 13:20:24.877827
6d4953ff-7d9c-4735-83f3-9d6cbb5667db	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	1c9eaa8c-2c55-4cd0-b552-ec003344536f	2025-12-17 13:20:24.880829	2025-12-17 13:20:24.880829
337ac809-40c0-47e2-8238-8a91222658fe	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	b60a7c54-9a90-4eb2-9fe7-f42ac1ffd52a	2025-12-17 13:20:24.885826	2025-12-17 13:20:24.885826
b596df6e-1cb8-4705-8de3-2b6bfd9e3f34	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	54e8a098-19b7-467f-94d6-2daa90149dee	2025-12-17 13:20:24.889029	2025-12-17 13:20:24.889029
6dc8677e-b2c4-4211-a1c2-34cd6809824d	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	e68ec1b3-96ee-4c35-99c2-0ca7b254ffc6	2025-12-17 13:20:24.893029	2025-12-17 13:20:24.893029
221d9af7-2cf5-482a-8ea6-6847b1ae7904	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	6ee8bd4c-fc79-4f7b-b143-db8d1d72e732	2025-12-17 13:20:24.897546	2025-12-17 13:20:24.897546
5c196b18-c94e-4e19-954d-72b1d71d04cf	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	ed3b8687-c636-43ef-a7fe-eded8e557a08	2025-12-17 13:20:24.903551	2025-12-17 13:20:24.903551
55963e99-5178-4d38-acd3-b64ba009abc3	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	9f2b9d5e-6830-4f69-84dc-3b9068aafe56	2025-12-17 13:20:24.906069	2025-12-17 13:20:24.906069
bb18c64b-ddd4-4cce-aaab-08d4a3f63627	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	3ad5b31d-80f5-455a-b4e4-ff5967a56f05	2025-12-17 13:20:24.909075	2025-12-17 13:20:24.909075
00d7fb98-7c05-4402-ba33-94be62e4facf	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	8e6635c9-119f-4fde-8788-a2552d584848	2025-12-17 13:20:24.912075	2025-12-17 13:20:24.912075
250c525e-5d1a-4e8c-a582-920757f047c0	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	d20eb58b-8f9c-45cc-9348-55570ac47920	2025-12-17 13:20:24.917776	2025-12-17 13:20:24.917776
dd388775-d3ca-4b37-bf01-e24a0d821a29	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	7f963daa-a724-4c92-950c-83ffa215f367	2025-12-17 13:20:24.92082	2025-12-17 13:20:24.92082
f81dccdd-bd43-45c7-99dd-f95dd809e310	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	fa33a10b-d47f-48eb-9d31-d19de167b1c0	2025-12-17 13:20:24.924184	2025-12-17 13:20:24.924184
5c67ab3b-cc5d-466e-8d26-93aabfbdb69a	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	1e4fa2ad-ede0-4659-819b-bd583abadbb1	2025-12-17 13:20:24.926699	2025-12-17 13:20:24.926699
f962f517-ff7c-4a40-82d4-c82843c4c411	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	72d75dfa-b484-4dae-97e7-9a3fe09278dd	2025-12-17 13:20:24.9297	2025-12-17 13:20:24.9297
5a2d23d1-bed6-46fc-a058-ddb0a9eee792	4638eee5-2b7b-46af-902d-569353af835c	9467767e-c991-49a9-bebb-0d8b5e327507	2025-12-17 16:08:17.434487	2025-12-17 16:08:17.434487
1a63d1c9-31c4-4f7c-af31-70773c4674c7	4638eee5-2b7b-46af-902d-569353af835c	4126c61b-117b-4eec-8758-9b8fcb6d9155	2025-12-17 16:08:17.421484	2025-12-17 16:09:05.181706
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name, created_at, updated_at) FROM stdin;
9c5c3325-6cd2-4e30-a53d-c3729023f5ae	ADMIN	2025-12-17 11:48:34.61601	2025-12-17 11:48:34.61601
174a8cf1-2dd5-40f2-bfe4-a1451dfa776d	LECTURER	2025-12-17 11:48:34.660656	2025-12-17 11:48:34.660656
a846d865-f808-4a30-b458-54d47cb07bad	STUDENT	2025-12-17 11:48:34.665655	2025-12-17 11:48:34.665655
4638eee5-2b7b-46af-902d-569353af835c	TEST_ROLE_2	2025-12-17 16:06:43.829786	2025-12-17 16:06:43.829786
e4e97e02-6b88-414c-ad89-80ea33b35a5b	TEST_ROLE_1_UPDATED	2025-12-17 16:06:43.744883	2025-12-17 16:07:01.675829
\.


--
-- Data for Name: specializations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.specializations (id, name, major_id, created_at, updated_at) FROM stdin;
dff3f28a-7aa8-4fb9-a312-b37d06fdb937	Mang va dich vu internet	a1b6c515-52a3-409b-9a65-4af199d58527	2025-11-20 14:01:59.837821+07	2025-11-20 14:01:59.837821+07
7d606dcb-40a7-4da9-aa47-190c037cb033	Internet	a1b6c515-52a3-409b-9a65-4af199d58527	2025-12-08 21:38:46.838843+07	2025-12-08 21:38:46.838843+07
927cf5f2-4749-4d49-94b5-e087dbc9db14	dien tu	e5188b15-530d-4efb-bfcd-fa90c9f385ea	2025-12-17 10:19:44.704201+07	2025-12-17 10:19:44.704201+07
ce8e3b4f-2611-48e5-9143-35d4fe77f8f6	TEST_SPEC_2	84b3da84-f02a-4f32-9906-100237ddde7d	2025-12-17 16:12:56.903648+07	2025-12-17 16:12:56.903648+07
711f48b2-4385-4db5-b9ce-9b48ff16cb2c	TEST_SPEC_1_UPDATED	84b3da84-f02a-4f32-9906-100237ddde7d	2025-12-17 16:12:56.844116+07	2025-12-17 16:14:50.490443+07
\.


--
-- Data for Name: student_credit_classes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_credit_classes (id, student_id, credit_class_id, scores, exam_schedule, created_at, updated_at) FROM stdin;
63dd9ffe-8d40-47f4-8e76-20ca21805103	cff4b2bd-99ce-4f43-9e92-a6d890d022ab	139ae00d-1b9c-4da2-b5af-03579cf7b95b	[{"name": "Chuyên cần", "score": 0, "percentage": 10}, {"name": "Kiểm tra", "score": 0, "percentage": 10}, {"name": "Thực hành", "score": 0, "percentage": 20}, {"name": "Bài tập", "score": 0, "percentage": 0}, {"name": "Điểm thi", "score": 0, "percentage": 60}]	\N	2025-12-17 10:09:17.172417+07	2025-12-17 10:09:17.172417+07
4d1fed62-5074-489b-810a-448e0542c449	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	139ae00d-1b9c-4da2-b5af-03579cf7b95b	{"items": [{"name": "Chuyen can", "score": 8, "percentage": 10}, {"name": "Kiem tra", "score": 7.5, "percentage": 20}]}	{"date": "2025-06-01", "room": "A101"}	2025-12-17 16:23:01.185489+07	2025-12-17 16:23:01.185489+07
3a5116c8-bfd7-4511-bdfe-c2dd0a1e1de6	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	ec50500a-b5e8-43d9-9615-2a4a4a4db256	{"items": [{"name": "Chuyen can", "score": 9, "percentage": 10}, {"name": "Kiem tra", "score": 8, "percentage": 20}]}	\N	2025-12-17 16:23:01.241133+07	2025-12-17 16:26:14.510715+07
\.


--
-- Data for Name: student_majors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_majors (id, student_id, major_id, specialization_id, created_at, updated_at) FROM stdin;
c98f7f2e-f715-4566-92e1-387fbdb05cf9	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	84b3da84-f02a-4f32-9906-100237ddde7d	ce8e3b4f-2611-48e5-9143-35d4fe77f8f6	2025-12-17 16:19:47.282412	2025-12-17 16:19:47.490098
\.


--
-- Data for Name: student_tuitions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_tuitions (id, student_id, tuition_id, endow, created_at, updated_at, paid) FROM stdin;
7b7325dd-11f0-44f0-89f1-4636fc1073a4	c795f5e4-8cda-47da-9953-34ef5eb179f4	558d9f95-e11b-4ff9-a2b4-df68b1792f94	0	2025-12-17 10:19:10.402338+07	2025-12-17 10:19:10.402338+07	\N
2c92a595-fd84-4ebd-8567-283b62e3ace7	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	a6a5ba0e-23ff-4c84-9501-b02f9835df4a	0	2025-12-17 16:21:11.862438+07	2025-12-17 16:21:11.862438+07	\N
823655de-cb20-463e-81c8-58cc2039ddfc	72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	558d9f95-e11b-4ff9-a2b4-df68b1792f94	15	2025-12-17 16:21:11.923016+07	2025-12-17 16:21:11.974951+07	\N
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (id, student_code, user_id, created_at, updated_at, class_id) FROM stdin;
cff4b2bd-99ce-4f43-9e92-a6d890d022ab	sv009	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-12-11 21:07:45.896274+07	2025-12-11 21:07:45.896274+07	\N
c795f5e4-8cda-47da-9953-34ef5eb179f4	sv008	f5d3a73e-1793-4345-846e-0c6c5b58fc3b	2025-12-17 10:06:22.803131+07	2025-12-17 10:06:22.804138+07	\N
72b3d7e2-d97b-465f-aa5e-9bfdd84dbc51	SVTEST001_UPD	1ef3f5ff-c0e2-4384-9168-cfce91123745	2025-12-17 16:18:44.176623+07	2025-12-17 16:19:01.773258+07	\N
\.


--
-- Data for Name: subjects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subjects (id, name, subject_code, major_id, specialization_id, number_of_credit, ingredient_secretion, semester, created_at, updated_at) FROM stdin;
3cbf960b-2ce7-4592-89ce-06d63ad43daf	Manager	sadsd	8b352b85-4e9e-4814-bb71-06d51580ac60	\N	2	[{"name": "Lý thuyết", "periods": 30}, {"name": "Thực hành", "periods": 15}, {"name": "Bài tập", "periods": 0}, {"name": "Tự học", "periods": 0}, {"name": "Bài tập lớn", "periods": 0}]	1234	2025-12-13 15:04:17.674114+07	2025-12-13 15:04:17.674114+07
31297203-8225-418b-b4e7-050e7acc8e86	Birthday	CS201	8b352b85-4e9e-4814-bb71-06d51580ac60	\N	0	[{"name": "Lý thuyết", "periods": 30}, {"name": "Thực hành", "periods": 15}, {"name": "Bài tập", "periods": 0}, {"name": "Tự học", "periods": 0}, {"name": "Bài tập lớn", "periods": 0}]	Học kỳ 2	2025-12-17 10:20:38.335402+07	2025-12-17 10:20:38.335402+07
d35b4594-8bb0-4062-86ad-ef41917cccb9	TEST_SUBJECT_2	TSUBJ2	84b3da84-f02a-4f32-9906-100237ddde7d	711f48b2-4385-4db5-b9ce-9b48ff16cb2c	3	{"midTerm": 0.4, "finalExam": 0.6}	2025-1	2025-12-17 16:15:20.48873+07	2025-12-17 16:15:20.48873+07
50dd8d4c-2701-4aac-bac9-a9c112de6c06	TEST_SUBJECT_1_UPDATED	TSUBJ1_UPDATED	84b3da84-f02a-4f32-9906-100237ddde7d	711f48b2-4385-4db5-b9ce-9b48ff16cb2c	4	{"midTerm": 0.4, "finalExam": 0.6}	2025-2	2025-12-17 16:15:20.420199+07	2025-12-17 16:15:20.551592+07
\.


--
-- Data for Name: teachers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teachers (id, teacher_code, user_id, created_at, updated_at) FROM stdin;
6a5fb6ba-08bb-4c66-b0c6-3476c863a1f6	GV-TEST-1764134870	27d91e1b-70dc-4d48-a2f5-34736908d154	2025-11-26 12:27:50.456574+07	2025-11-26 12:27:50.456574+07
69faa257-4252-4b01-9c99-1bd7535d54ef	gv009	c5db9691-ecf6-464d-aa83-1a173f603804	2025-12-17 10:06:34.897453+07	2025-12-17 10:06:34.897453+07
ddd9840b-7f1e-4371-b411-a5001c86a3a4	GVTEST001_UPD	f59680dd-3773-439b-a7a0-a75237177d5c	2025-12-17 16:21:34.880231+07	2025-12-17 16:21:34.931499+07
\.


--
-- Data for Name: time_registers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.time_registers (id, type_semester, type_register, open_time, end_time, created_at, updated_at, version) FROM stdin;
ae689147-b73d-4bce-b6f3-174ee2a8f6a4	FALL	subject_registration	2025-09-01T08:00:00	2025-09:10T18:00:00	2025-12-17 16:16:50.578072+07	2025-12-17 16:16:50.578072+07	\N
0459bb1d-5bca-4e08-9d3b-da89126efd7d	SPRING	subject_registration	2025-04-02T08:00:00	2025-04-11T18:00:00	2025-12-17 16:16:50.518756+07	2025-12-17 16:17:04.139948+07	\N
eec2ca7c-8b36-4632-8ae4-6ad1700031ab	SPRING	COURSE	2025-01-01T08:00:00	2025-01-10T18:00:00	2025-11-21 10:30:29.945387+07	2025-11-21 10:30:29.945387+07	0
a8e3f8a7-d09b-49c5-8319-79a5e4b40753	SPRING	COURSE	2025-02-01T08:00:00	2025-02-10T18:00:00	2025-11-21 10:30:29.94813+07	2025-11-21 10:30:29.94813+07	0
9c758d34-c2bc-4c0a-8f3a-3c233e58e738	SPRING	EXAM	2025-03-01T08:00:00	2025-03-10T18:00:00	2025-11-21 10:30:29.952049+07	2025-11-21 10:30:29.952049+07	0
\.


--
-- Data for Name: tuitions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tuitions (id, semester, year, academic_year, created_at, updated_at, price) FROM stdin;
a6a5ba0e-23ff-4c84-9501-b02f9835df4a	Fall	2024	2024-2025	2025-11-23 15:37:07.773209+07	2025-11-23 15:37:07.773209+07	1500000
558d9f95-e11b-4ff9-a2b4-df68b1792f94	Học kỳ 1	2025	2024-2028	2025-12-17 10:18:20.755465+07	2025-12-17 10:18:53.558052+07	4000
71fb1829-2e08-4374-acff-055fe9b73916	2	2025	2025-2026	2025-12-17 16:17:30.160336+07	2025-12-17 16:17:30.160336+07	1500000
6762aea3-6ea7-468b-b37f-4b39b00d7a12	1	2025	2025-2026	2025-12-17 16:17:30.107146+07	2025-12-17 16:17:30.272376+07	1200000
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (id, user_id, role_id, created_at, updated_at) FROM stdin;
0c08b521-48ca-4916-84ea-9bd547d5c94c	c6774fa6-19e7-4c17-932d-19e0883631d8	9c5c3325-6cd2-4e30-a53d-c3729023f5ae	2025-12-17 11:48:34.773073	2025-12-17 11:48:34.773073
90b7581f-c240-4f2c-8234-a86935bb8852	f5d3a73e-1793-4345-846e-0c6c5b58fc3b	174a8cf1-2dd5-40f2-bfe4-a1451dfa776d	2025-12-17 14:07:07.435993	2025-12-17 14:07:07.435993
3b0cb7db-ae2a-44d3-a93a-3411982cabef	b2279e6e-b274-4425-a85b-c829a1f94176	a846d865-f808-4a30-b458-54d47cb07bad	2025-12-17 14:42:35.162603	2025-12-17 14:42:35.162603
4fd3c29d-3f26-4605-be48-f54fe81971da	f59680dd-3773-439b-a7a0-a75237177d5c	174a8cf1-2dd5-40f2-bfe4-a1451dfa776d	2025-12-17 16:11:10.780708	2025-12-17 16:11:10.780708
2b14b14e-3e93-4bd5-b313-79feb2e74f35	1ef3f5ff-c0e2-4384-9168-cfce91123745	a846d865-f808-4a30-b458-54d47cb07bad	2025-12-17 16:11:10.788702	2025-12-17 16:11:10.788702
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password_hash, name, phone, date_of_birth, gender, address, status, academic_year, education_level, is_online, created_at, updated_at) FROM stdin;
c5db9691-ecf6-464d-aa83-1a173f603804	tran.thi.binh@student.edu.vn	$2a$10$N9qo8uLOickgx2ZMRZoMye7FrYizs8F9dqe3xFNQxpMFvW3M3J8Lm	Trần Thị Bình	0912345678	2008-08-20	Female	456 Đường Nguyễn Huệ, Quận 3, TP.HCM	Active	2024-2025	Grade 10	f	2025-11-10 09:46:35.155914	2025-11-10 09:46:35.155914
f5d3a73e-1793-4345-846e-0c6c5b58fc3b	minhdz@gmail.com	$2a$10$f.8XVggy84csZce4PHWq5eufB98WQijyXfTWgkm99.FmpoaxyTfcK	Đỗ Tuấn Minh	0968972915	2025-06-17	Nam	Phùng Khoang	Teaching	2024-2028	Kỹ sư	f	2025-12-17 10:05:19.040199	2025-12-17 14:58:16.703709
b2279e6e-b274-4425-a85b-c829a1f94176	anhtus@gmail.com	$2a$10$dZ43qyT3RNYaaExQI1kdqOak/XTk5XcffRH1XxJcztR5C2WQYtCYW	Hoàng Anh Tú	0968972911	2025-12-05	Nam	Nam Định	Studying	2024-2028	Kỹ sư	f	2025-12-17 14:42:27.968903	2025-12-17 14:58:44.718891
047a31af-368f-43a0-b6a3-36972669544d	bduy@gmail.com	$2a$10$QzAOJ1mlOHJCO3xeub94Le21lH7VFfNXQNrbb9Ilw.qDirblARAiG	Nguyễn Bá Duy	0987654321	2006-07-14	Nam	Xã Dương Hòa	Studying	2024-2028	Kỹ sư	f	2025-12-08 19:09:58.940956	2025-12-08 19:09:58.940956
27d91e1b-70dc-4d48-a2f5-34736908d154	levi2k3ds@gmail.com	$2a$10$aX5aDLuz47/WLHELZhwFSuhYgCn29Jo83fW1HPg4WcaQlRBRHlQjK	Nguyễn Văn An	0901234567	1985-05-15	Male	123 Đường Lê Lợi, Quận 1, TP.HCM	Active	2024-2025	Teacher	t	2025-11-10 09:46:05.847853	2025-12-13 11:01:03.882491
1ef3f5ff-c0e2-4384-9168-cfce91123745	test.student1@example.com	$2a$10$xQvYisInhTIKWLcxqk67reJCwze/IlbOWnh7kcBmQRQ0CAHo3Ph4S	Test Student 1	0900000003	2003-03-03	Nam	Test Address 3	ACTIVE	2023	Dai hoc	f	2025-12-17 16:09:37.937181	2025-12-17 16:09:37.937181
d4a9de0c-5525-4d60-8d79-fb11a6b6fee0	test.admin1.updated@example.com	$2a$10$QPfD0w55dG.liJ9KEfcFEu9dzX2aSokmlghwhRLj6wjSs3DFrg1CC	Test Admin 1 Updated	0900000001	1995-01-01	Nam	Updated Address 1	ACTIVE	2025	Dai hoc	f	2025-12-17 16:09:37.765313	2025-12-17 16:09:55.191275
81a1a826-4061-44b0-b495-45626edf9036	test.student2@example.com	$2a$10$sUZ2fQF0sbydcpSO1NvrneKgks4ZglZSLOjhSfUFkfo1jSpBQjg.q	Test Student 2	0900000005	2004-04-04	Nam	Test Address 5	ACTIVE	2023	Dai hoc	f	2025-12-17 16:18:44.122902	2025-12-17 16:18:44.122902
f59680dd-3773-439b-a7a0-a75237177d5c	test.lecturer1@example.com	$2a$10$0djfrOP0eU4PK06Xdao02.bpobem2BTVqG8AZqZ94Q4PXFW8JSFzi	Test Lecturer 1	0900000002	1990-02-02	Nu	Test Address 2	ACTIVE	2020	Thac si	t	2025-12-17 16:09:37.855434	2025-12-17 16:25:03.28598
c6774fa6-19e7-4c17-932d-19e0883631d8	superadmin@gmail.com	$2a$10$S0x2Qn4STAKDT284TEng9O/aMyXO0oEc1sm2bPlGn1katB4R5OR7W	Super Admin	0123456789	1990-01-01	Nam	System Address	ACTIVE	\N	\N	t	2025-12-17 11:48:34.762095	2025-12-18 14:46:49.770685
\.


--
-- Name: password_reset_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_token_id_seq', 1, false);


--
-- Name: aspiration_registers aspiration_registers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aspiration_registers
    ADD CONSTRAINT aspiration_registers_pkey PRIMARY KEY (id);


--
-- Name: blacklist_token blacklist_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blacklist_token
    ADD CONSTRAINT blacklist_token_pkey PRIMARY KEY (id);


--
-- Name: blacklist_token blacklist_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blacklist_token
    ADD CONSTRAINT blacklist_token_token_key UNIQUE (token);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: credit_classes credit_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.credit_classes
    ADD CONSTRAINT credit_classes_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: majors majors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.majors
    ADD CONSTRAINT majors_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: password_tokens password_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_tokens
    ADD CONSTRAINT password_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_tokens password_tokens_reset_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_tokens
    ADD CONSTRAINT password_tokens_reset_token_key UNIQUE (reset_token);


--
-- Name: permissions permissions_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_name_key UNIQUE (name);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: prerequisite_subjects prerequisite_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prerequisite_subjects
    ADD CONSTRAINT prerequisite_subjects_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: specializations specializations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specializations
    ADD CONSTRAINT specializations_pkey PRIMARY KEY (id);


--
-- Name: student_credit_classes student_credit_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_credit_classes
    ADD CONSTRAINT student_credit_classes_pkey PRIMARY KEY (id);


--
-- Name: student_majors student_majors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_majors
    ADD CONSTRAINT student_majors_pkey PRIMARY KEY (id);


--
-- Name: student_tuitions student_tuitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_tuitions
    ADD CONSTRAINT student_tuitions_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: time_registers time_registers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.time_registers
    ADD CONSTRAINT time_registers_pkey PRIMARY KEY (id);


--
-- Name: tuitions tuitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tuitions
    ADD CONSTRAINT tuitions_pkey PRIMARY KEY (id);


--
-- Name: blacklist_token uk_blacklist_token_token; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blacklist_token
    ADD CONSTRAINT uk_blacklist_token_token UNIQUE (token);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: password_reset_token ukf90ivichjaokvmovxpnlm5nin; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT ukf90ivichjaokvmovxpnlm5nin UNIQUE (user_id);


--
-- Name: password_reset_token ukg0guo4k8krgpwuagos61oc06j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT ukg0guo4k8krgpwuagos61oc06j UNIQUE (token);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: aspiration_registers aspiration_registers_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aspiration_registers
    ADD CONSTRAINT aspiration_registers_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: classes classes_major_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(id);


--
-- Name: classes classes_specialization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_specialization_id_fkey FOREIGN KEY (specialization_id) REFERENCES public.specializations(id);


--
-- Name: classes classes_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: credit_classes credit_classes_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.credit_classes
    ADD CONSTRAINT credit_classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: departments departments_major_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(id);


--
-- Name: password_reset_token fk83nsrttkwkb6ym0anu051mtxn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fk83nsrttkwkb6ym0anu051mtxn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: password_tokens password_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_tokens
    ADD CONSTRAINT password_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: role_permissions role_permissions_permission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id);


--
-- Name: role_permissions role_permissions_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: specializations specializations_major_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specializations
    ADD CONSTRAINT specializations_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(id);


--
-- Name: student_credit_classes student_credit_classes_credit_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_credit_classes
    ADD CONSTRAINT student_credit_classes_credit_class_id_fkey FOREIGN KEY (credit_class_id) REFERENCES public.credit_classes(id);


--
-- Name: student_credit_classes student_credit_classes_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_credit_classes
    ADD CONSTRAINT student_credit_classes_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: student_tuitions student_tuitions_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_tuitions
    ADD CONSTRAINT student_tuitions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: student_tuitions student_tuitions_tuition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_tuitions
    ADD CONSTRAINT student_tuitions_tuition_id_fkey FOREIGN KEY (tuition_id) REFERENCES public.tuitions(id);


--
-- Name: students students_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: subjects subjects_major_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_major_id_fkey FOREIGN KEY (major_id) REFERENCES public.majors(id);


--
-- Name: subjects subjects_specialization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_specialization_id_fkey FOREIGN KEY (specialization_id) REFERENCES public.specializations(id);


--
-- Name: teachers teachers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_roles user_roles_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles user_roles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

