export const ROUTE_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  USERS: "/dashboard/users",
  STUDENTS: "/dashboard/students",
  LECTURERS: "/dashboard/lecturers",
  NEWS: "/dashboard/news",
  MAJORS: "/dashboard/majors",
  DEPARTMENTS: "/dashboard/departments",
  SPECIALIZATIONS: "/dashboard/specializations",
  CLASSES: "/dashboard/classes",
  CREDIT_CLASSES: "/dashboard/credit-classes",
  STUDENT_CREDIT_CLASSES: "/dashboard/student-credit-classes",
  SUBJECTS: "/dashboard/subjects",
  ASPIRATION_REGISTERS: "/dashboard/aspiration-registers",
  NOTIFICATIONS: "/dashboard/notifications",
  TUITIONS: "/dashboard/tuitions",
  STUDENT_TUITIONS: "/dashboard/student-tuitions",
  TIME_REGISTERS: "/dashboard/time-registers",
  PREREQUISITE_SUBJECTS: "/dashboard/prerequisite-subjects",
  PROFILE: "/dashboard/profile",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  PUBLIC_HOME: "/public/home",
  PUBLIC_ADMIN_NOTIFICATIONS: "/public/home/admin-notifications",
} as const;
