export const ROUTE_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  USERS: "/dashboard/users",
  STUDENTS: "/dashboard/students",
  LECTURERS: "/dashboard/lecturers",
  NEWS: "/dashboard/news",
  MAJORS: "/dashboard/majors",
  DEPARTMENTS: "/dashboard/departments",
  SPECIALIZATIONS: "/dashboard/specializations",
  NOTIFICATIONS: "/dashboard/notifications",
  TUITIONS: "/dashboard/tuitions",
  TIME_REGISTERS: "/dashboard/time-registers",
  PREREQUISITE_SUBJECTS: "/dashboard/prerequisite-subjects",
  PROFILE: "/dashboard/profile",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
} as const;
