spring.application.name=server

# CORS Configuration - Cho phép tất cả origins
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.exposed-headers=*
spring.web.cors.max-age=3600

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/education_management_system
spring.datasource.username=postgres
spring.datasource.password=mhi3172003

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==================================
# CẤU HÌNH GỬI EMAIL (DÙNG GMAIL)
# ==================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=levi2k3ds@gmail.com
spring.mail.password=zbkx cxzl geis tnpn
# Cấu hình thuộc tính JavaMail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=Q2hhbmdlTWVQYXNzd29yZF9qd3RzZWNyZXQxMjM0NTY=
app.jwt.expiration-ms=86400000

jwt.secret=sL5kD7rY4bF9sMfC6tPz9Qw2xN8aH3uE1vKpL0iTgU4yJrQpFqWbZmTnGhRdSlOa
